### ISSUE TITLE
user_type

### ISSUE THREAD

**Issue by puchala-mag** [tiadal/freeopengym.com#3]
Hello team of freeopengym,

we want to ask, if the separation of User into Teacher and Not-Teacher (we've called it "Participants") is really necessary. As we understood every User can become a Teacher and a Teacher can still participate on other classes like an ordinary Participant, so the only one attribute, that make them different is the list of events (we also suggest changing this name to "course") held. Maybe we could give every User a possibility to open his own event and as he does it, just tag him as a Teacher (display a word "teacher" near the username) and not making from Teacher and Participant different types?

Greeting

**Comment by tiadal** [comment]
Hello, as you said each user can be either a teacher or a participant. 
We would like to keep them separated since they are different entities also legally. But for this project is it fine if you consider them as "users" and maybe add a IsTeacher:bool parameter

**Comment by Rudolchr** [comment]
> We would like to keep them separated since they are different entities also legally.

So this means a teacher cannot join courses as participant?

**Comment by tiadal** [comment]
Imagine if you are buying stuff on amazon or selling stuff to amazon. Even if you are the same "person" there are different laws and regulations involved. 

So theoretically a person could do both, but on the platform, they should be separated. Basically all Users = all teachers + all participants. 

you could implement it in different ways, but please keep in mind this split.

Thanks

**Comment by puchala-mag** [comment]
What about follow then? Is it only possible that a participant follows a teacher or every user can follow every user?

**Comment by tiadal** [comment]
I will try to clarify all in order to make it more clear:
Users = Teachers + Partecipiants
The only teacher can offer courses/classes
you could implement it in different ways, but please keep in mind this split.

**FollowUnfollow**
it's basically a list of all the users that a certain user xyz follows. You could split in 2 like "followedTeachers" and "followedPartecipiants", if you think it makes more sense from the model point of view.
Imagine in the future we would add a chat and picture uploading, we would like every user to interact with others.

**sport or should the user just write it in the text field?**
**Is there by class features "spots available" or "sports available"?**
You could add spots available, it's not a must-have feature for the app launch.
sports available is more the category of the course/class, feel free to add it. Maybe a list is better.
